/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pairoffives;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;

/**
 *
 * @author Tony
 */
public class spelersForm extends javax.swing.JFrame {

    /**
     * Creates new form spelersForm
     */
    
    DefaultListModel jlistmodel = new DefaultListModel();
    
    public void spelersoverzicht(){
        
         try {
            
            Connection conn = SimpleDataSourceV2.getConnection();

            
            Statement stat = conn.createStatement();

            ResultSet result = stat.executeQuery("select id, naam, adres, postcode, woonplaats, telnr, email, gewonnen, verloren, rating from speler");

            while (result.next()) {

                ModelItem item = new ModelItem();

                item.id = result.getInt("id");
                item.naam = result.getString("naam");
                item.adres = result.getString("adres");
                item.postcode = result.getString("postcode");
                item.woonplaats = result.getString("woonplaats");
                item.telnr = result.getInt("telnr");
                item.email = result.getString("email");
                item.gewonnen = result.getInt("gewonnen");
                item.verloren = result.getInt("verloren");
                item.rating = result.getDouble("rating");
   
                jlistmodel.addElement(item);
                
            }
            
            jList1.setModel(jlistmodel);

        } catch (Exception ex) {
            
            System.out.println(ex);
        }
        
        
    }
    
    
    
    public spelersForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(735, 427));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Naam:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 90, 60, 14);

        jLabel2.setText("Adres:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 130, 50, 14);

        jLabel3.setText("Postcode:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 170, 70, 14);

        jLabel4.setText("Woonplaats:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 210, 80, 14);

        jLabel5.setText("Telnr:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 250, 60, 14);

        jLabel6.setText("Email:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 290, 50, 14);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 230, 0, 0);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(110, 80, 129, 25);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(110, 120, 129, 25);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(110, 160, 129, 25);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(110, 200, 129, 25);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(110, 240, 129, 25);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(110, 280, 129, 25);

        jButton1.setText("Opslaan");
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 350, 80, 23);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Spelers overzicht");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(420, 20, 160, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Speler aanmaken");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(70, 20, 160, 22);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(410, 60, 200, 130);

        jButton2.setText("Aanpassen");
        getContentPane().add(jButton2);
        jButton2.setBounds(410, 210, 120, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(spelersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(spelersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(spelersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(spelersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new spelersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
